version: "3.3"
services:
  mongodb:
    image: mongo:5.0
    container_name: my_mongo
    volumes:
      - ./config:/data/db  
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: trustscore_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  