name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - pipeline
  pull_request:
    branches:
      - main
      - develop
      - pipeline

jobs:
  test-and-build:
    name: Test, Build & Push Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration Python (si des tests existent)
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install -r scrapping_app/requirements.txt
          pip install pytest

      # Étape 3 : Lancer les tests (optionnel)
      # - name: Run tests
      #   run: pytest tests/

      # Étape 4 : Configuration Docker
      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker images
        run: |
          # Construire et tagger les images Docker
          docker build -t $DOCKER_USERNAME/flask_api:latest -f flask_api/Dockerfile ./flask_api
          docker build -t $DOCKER_USERNAME/dash_app:latest -f dash_app/Dockerfile ./dash_app

          # Pousser les images vers Docker Hub
          docker push $DOCKER_USERNAME/scraper:latest
          docker push $DOCKER_USERNAME/flask_api:latest
          docker push $DOCKER_USERNAME/dash_app:latest
